using Amazon;
using Amazon.BedrockAgentRuntime;
using Amazon.BedrockAgentRuntime.Model;
using Amazon.Runtime;
using HospitalityAI.Domain.Dtos;

namespace HospitalityAI.Api.Services;

public class OperationsBedrockService
{
    private readonly IAmazonBedrockAgentRuntime _bedrockAgentRuntime;
    private readonly string _agentId;
    private readonly string _agentAliasId;

    public OperationsBedrockService(IConfiguration configuration)
    {
        var region = configuration["OperationsBedrock:Region"] ?? "us-east-1";

        // AgentArn format: arn:aws:bedrock:<region>:<account>:agent/<agentId>
        var agentArn = configuration["OperationsBedrock:AgentArn"]
            ?? throw new InvalidOperationException("Operations Bedrock agent ARN is not configured.");

        if (string.IsNullOrWhiteSpace(agentArn))
            throw new InvalidOperationException("Operations Bedrock agent ARN is not configured.");

        _agentId = agentArn.Split('/').Last();
        _agentAliasId = configuration["OperationsBedrock:AgentAliasId"] ?? "TSTALIASID";

        var awsRegion = RegionEndpoint.GetBySystemName(region);

        // Use explicit credentials when configured (local dev), otherwise fall
        // back to the default credential chain (IAM role, env vars, AWS profile).
        var accessKey = configuration["OperationsBedrock:AccessKey"];
        var secretKey = configuration["OperationsBedrock:SecretKey"];

        if (!string.IsNullOrWhiteSpace(accessKey) && !string.IsNullOrWhiteSpace(secretKey)
            && accessKey != "YOUR_AWS_ACCESS_KEY_ID")
        {
            var credentials = new BasicAWSCredentials(accessKey, secretKey);
            _bedrockAgentRuntime = new AmazonBedrockAgentRuntimeClient(credentials, awsRegion);
        }
        else
        {
            _bedrockAgentRuntime = new AmazonBedrockAgentRuntimeClient(awsRegion);
        }
    }

    /// <summary>
    /// Returns a priority recommendation for an operations issue described by <paramref name="description"/>.
    /// </summary>
    public async Task<PriorityRecommendationDto> GetPriorityRecommendationAsync(
        string description, CancellationToken ct = default)
    {
        await Task.CompletedTask;
        throw new NotImplementedException();
    }

    /// <summary>
    /// Returns an operations forecast generated by the Bedrock agent.
    /// </summary>
    public async Task<ForecastDto> GetOperationsForecastAsync(CancellationToken ct = default)
    {
        await Task.CompletedTask;
        throw new NotImplementedException();
    }

    // -----------------------------------------------------------------------
    // Shared helper — invokes the agent and collects all PayloadPart chunks
    // -----------------------------------------------------------------------
    private async Task<string> InvokeAgentAsync(string inputText, CancellationToken ct, string? sessionId = null)
    {
        var request = new InvokeAgentRequest
        {
            AgentId = _agentId,
            AgentAliasId = _agentAliasId,
            SessionId = sessionId ?? Guid.NewGuid().ToString(),
            InputText = inputText
        };

        var response = await _bedrockAgentRuntime.InvokeAgentAsync(request, ct);

        // ResponseStream extends EnumerableEventOutputStream<IEventStreamEvent, ...>
        // which implements IEnumerable — iterate with a plain foreach.
        var resultBuilder = new System.Text.StringBuilder();
        foreach (var ev in response.Completion)
        {
            if (ev is PayloadPart payload && payload.Bytes != null)
            {
                resultBuilder.Append(System.Text.Encoding.UTF8.GetString(
                    payload.Bytes.ToArray()));
            }
        }

        return resultBuilder.Length > 0
            ? resultBuilder.ToString()
            : "No response from Bedrock agent.";
    }

    // -----------------------------------------------------------------------
    // Static helpers
    // -----------------------------------------------------------------------

    /// <summary>
    /// Scans the agent response case-insensitively for priority tokens in precedence order.
    /// Returns "Medium" if no token is found. Never throws, never returns null.
    /// </summary>
    internal static string ParsePriority(string agentResponse)
    {
        if (agentResponse.Contains("critical", StringComparison.OrdinalIgnoreCase)) return "Critical";
        if (agentResponse.Contains("high",     StringComparison.OrdinalIgnoreCase)) return "High";
        if (agentResponse.Contains("medium",   StringComparison.OrdinalIgnoreCase)) return "Medium";
        if (agentResponse.Contains("low",      StringComparison.OrdinalIgnoreCase)) return "Low";
        return "Medium";
    }

    /// <summary>
    /// Builds a deterministic, date-scoped session ID.
    /// Format: "{prefix}-{yyyyMMdd}" e.g. "ops-priority-20250101"
    /// </summary>
    internal static string BuildSessionId(string prefix, DateTimeOffset now)
        => $"{prefix}-{now:yyyyMMdd}";
}
